org.gradle.jvmargs=-Xmx4G

mod_version=1.9.5
maven_group=baritone
archives_base_name=baritone

java_version=25

minecraft_version=26.1.2

neoforge_version=26.1.2.66-beta

fabric_loader_version=0.18.4
fabric_api_version=0.145.4+26.1.2

nether_pathfinder_version=1.6

// These dependencies are used for common and tweaker
// while mod loaders usually ship their own version
mixin_version=0.8.7
asm_version=9.7
